version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"
  web:
    build: .
    command: sh -c "uvicorn app.main:app --reload --port=8000 --host=0.0.0.0"
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/app